# Minimax GSP: Python Translation Test

This notebook exercises the translated functions on a small random GSP Ising model.

In [1]:
import numpy as np
from minimax_gsp import random_gsp_ising, exact_ising, find_gsp_update, correlations_gsp_01
import time


n = 500
start_time = time.perf_counter()
# Your code here
J_true, h_true = random_gsp_ising(n)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"Time taken: {elapsed_time:.4f} seconds")

mean, corr, _, _ = correlations_gsp_01(J_true, h_true)
start_time = time.perf_counter()
h_hat, J_hat, ent, ents = find_gsp_update(mean, corr)
end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"Time taken: {elapsed_time:.4f} seconds")
mean1, corr2, _, _ = correlations_gsp_01(J_hat, h_hat)

print('J difference (fro):', np.linalg.norm(J_hat - J_true))
print('h difference (l2):', np.linalg.norm(h_hat - h_true))
print('corr difference (l2):', np.linalg.norm(corr - corr2))
print('Final entropy estimate:', ent)

Time taken: 0.0357 seconds
Time taken: 219.0656 seconds
J difference (fro): 15.749251432742142
h difference (l2): 14.971935322535295
corr difference (l2): 0.1456023266450119
Final entropy estimate: 244.29364394213545


In [2]:
# Inspect the inferred coupling matrix
J_hat

array([[ 0.        , -1.26275557, -0.43033961, ...,  0.01741643,
        -0.00615143,  0.56547947],
       [-1.26275557,  0.        , -0.78312921, ...,  0.        ,
         0.        , -1.14290502],
       [-0.43033961, -0.78312921,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.01741643,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.00615143,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56547947, -1.14290502,  0.        , ...,  0.        ,
         0.        ,  0.        ]], shape=(50, 50))

In [3]:
J_true

array([[ 0.        , -1.26923145, -0.46716198, ...,  0.        ,
         0.        ,  0.56547947],
       [-1.26923145,  0.        , -0.78312921, ...,  0.        ,
         0.        , -1.14290502],
       [-0.46716198, -0.78312921,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56547947, -1.14290502,  0.        , ...,  0.        ,
         0.        ,  0.        ]], shape=(50, 50))

In [11]:
corr

array([[0.95022372, 0.94957292, 0.38416411, ..., 0.44195044, 0.6201065 ,
        0.62474176],
       [0.94957292, 0.9992924 , 0.41393486, ..., 0.46396321, 0.6521106 ,
        0.65708275],
       [0.38416411, 0.41393486, 0.41433581, ..., 0.17261396, 0.26984206,
        0.27240005],
       ...,
       [0.44195044, 0.46396321, 0.17261396, ..., 0.46428296, 0.30301994,
        0.30525169],
       [0.6201065 , 0.6521106 , 0.26984206, ..., 0.30301994, 0.65256751,
        0.42904214],
       [0.62474176, 0.65708275, 0.27240005, ..., 0.30525169, 0.42904214,
        0.65746697]], shape=(500, 500))

In [12]:
corr2

array([[0.95022372, 0.94955029, 0.38416411, ..., 0.44194991, 0.62010638,
        0.62474059],
       [0.94955029, 0.9992924 , 0.4140692 , ..., 0.46395227, 0.65210569,
        0.65708275],
       [0.38416411, 0.4140692 , 0.41433581, ..., 0.17261512, 0.26984197,
        0.27241515],
       ...,
       [0.44194991, 0.46395227, 0.17261512, ..., 0.46428296, 0.30301994,
        0.30525047],
       [0.62010638, 0.65210569, 0.26984197, ..., 0.30301994, 0.65256751,
        0.42904158],
       [0.62474059, 0.65708275, 0.27241515, ..., 0.30525047, 0.42904158,
        0.65746697]], shape=(500, 500))